idea:
    build: .
    labels:
        org.kurron.description: "JetBrains CLion C++ IDE"
        org.kurron.version: "1.2.1"
    container_name: "clion"
    net: "host"
    volumes:
        - /tmp/.X11-unix:/tmp/.X11-unix
        - /home/vagrant:/home/developer
    environment:
        DISPLAY: unix:0.0
    user: 1000:1000
